namespace steam_hidapi.net
{
    public enum NeptuneControllerButton
    {
        BtnX = 1,
        BtnY = 2,
        BtnA = 3,
        BtnB = 4,
        BtnMenu = 5,
        BtnOptions = 6,
        BtnSteam = 7,
        BtnQuickAccess = 8,
        BtnDpadUp = 9,
        BtnDpadLeft = 10,
        BtnDpadRight = 11,
        BtnDpadDown = 12,
        BtnL1 = 13,
        BtnR1 = 14,
        BtnL2 = 15,
        BtnR2 = 16,
        BtnL4 = 17,
        BtnR4 = 18,
        BtnL5 = 19,
        BtnR5 = 20,
        BtnRPadPress = 21,
        BtnLPadPress = 22,
        BtnRPadTouch = 23,
        BtnLPadTouch = 24,
        BtnRStickPress = 25,
        BtnLStickPress = 26,
        BtnRStickTouch = 27,
        BtnLStickTouch = 28,
    }

    public enum NeptuneControllerAxis
    {
        LeftStickX = 1,
        LeftStickY = 2,
        RightStickX = 3,
        RightStickY = 4,
        LeftPadX = 5,
        LeftPadY = 6,
        RightPadX = 7,
        RightPadY = 8,
        LeftPadPressure = 9,
        RightPadPressure = 10,
        L2 = 11,
        R2 = 12,
        GyroAccelX = 13,
        GyroAccelY = 14,
        GyroAccelZ = 15,
        GyroRoll = 16,
        GyroPitch = 17,
        GyroYaw = 18,
        Q1 = 19,
        Q2 = 20,
        Q3 = 21,
        Q4 = 22,
    }
}
