//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandheldCompanion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandheldCompanion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handheld Companion provides gyroscope and accelerometer support to the AYA NEO 2020 and 2021 models through a virtual DualShock 4 controller. If the service is enabled, embedded controller will be cloaked to applications outside the whitelist. If the service is disabled, embedded controller will be uncloaked and virtual DualShock 4 controller disabled. Handheld Companion relies on ViGEmBus driver and ViGEmClient libraries as well as HidHide kernel-mode filter driver. Motion control algorithms are based on w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutPage_AboutDescription {
            get {
                return ResourceManager.GetString("AboutPage_AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        public static string AboutPage_Accelerometer {
            get {
                return ResourceManager.GetString("AboutPage_Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string AboutPage_Author {
            get {
                return ResourceManager.GetString("AboutPage_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string AboutPage_Contributors {
            get {
                return ResourceManager.GetString("AboutPage_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AboutPage_Description {
            get {
                return ResourceManager.GetString("AboutPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string AboutPage_Donate {
            get {
                return ResourceManager.GetString("AboutPage_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer.
        /// </summary>
        public static string AboutPage_Gyrometer {
            get {
                return ResourceManager.GetString("AboutPage_Gyrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer.
        /// </summary>
        public static string AboutPage_Inclinometer {
            get {
                return ResourceManager.GetString("AboutPage_Inclinometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string AboutPage_NotApplicable {
            get {
                return ResourceManager.GetString("AboutPage_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Links.
        /// </summary>
        public static string AboutPage_RelatedLinks {
            get {
                return ResourceManager.GetString("AboutPage_RelatedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Name.
        /// </summary>
        public static string AboutPage_SensorName {
            get {
                return ResourceManager.GetString("AboutPage_SensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Specification.
        /// </summary>
        public static string AboutPage_SensorSpecification {
            get {
                return ResourceManager.GetString("AboutPage_SensorSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string AboutPage_SourceCode {
            get {
                return ResourceManager.GetString("AboutPage_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AboutPage_Version {
            get {
                return ResourceManager.GetString("AboutPage_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string AboutPage_Wiki {
            get {
                return ResourceManager.GetString("AboutPage_Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloak device.
        /// </summary>
        public static string ControllerPage_CloakDevice {
            get {
                return ResourceManager.GetString("ControllerPage_CloakDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the physical controller visibility to other applications.
        /// </summary>
        public static string ControllerPage_CloakDeviceDesc {
            get {
                return ResourceManager.GetString("ControllerPage_CloakDeviceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ControllerPage_Connect {
            get {
                return ResourceManager.GetString("ControllerPage_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device cloaking.
        /// </summary>
        public static string ControllerPage_DeviceCloaking {
            get {
                return ResourceManager.GetString("ControllerPage_DeviceCloaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input devices.
        /// </summary>
        public static string ControllerPage_InputDevices {
            get {
                return ResourceManager.GetString("ControllerPage_InputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncloak on close.
        /// </summary>
        public static string ControllerPage_UncloakOnClose {
            get {
                return ResourceManager.GetString("ControllerPage_UncloakOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore visibility of the physical controller to other applications on service exit.
        /// </summary>
        public static string ControllerPage_UncloakOnCloseDesc {
            get {
                return ResourceManager.GetString("ControllerPage_UncloakOnCloseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration strength.
        /// </summary>
        public static string ControllerPage_VibrationStrength {
            get {
                return ResourceManager.GetString("ControllerPage_VibrationStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change controller vibration strength.
        /// </summary>
        public static string ControllerPage_VibrationStrengthExpl {
            get {
                return ResourceManager.GetString("ControllerPage_VibrationStrengthExpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_navAbout {
            get {
                return ResourceManager.GetString("MainWindow_navAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string MainWindow_navController {
            get {
                return ResourceManager.GetString("MainWindow_navController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string MainWindow_navOverlay {
            get {
                return ResourceManager.GetString("MainWindow_navOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string MainWindow_navProfiles {
            get {
                return ResourceManager.GetString("MainWindow_navProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Service.
        /// </summary>
        public static string MainWindow_serviceDeploy {
            get {
                return ResourceManager.GetString("MainWindow_serviceDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service.
        /// </summary>
        public static string MainWindow_serviceRemove {
            get {
                return ResourceManager.GetString("MainWindow_serviceRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service.
        /// </summary>
        public static string MainWindow_serviceStart {
            get {
                return ResourceManager.GetString("MainWindow_serviceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Service.
        /// </summary>
        public static string MainWindow_serviceStop {
            get {
                return ResourceManager.GetString("MainWindow_serviceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string OverlayPage_Alignment {
            get {
                return ResourceManager.GetString("OverlayPage_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the 3D overlay controller alignment.
        /// </summary>
        public static string OverlayPage_AlignmentDesc {
            get {
                return ResourceManager.GetString("OverlayPage_AlignmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the trackpads overlay alignment.
        /// </summary>
        public static string OverlayPage_AlignmentTrackpadDesc {
            get {
                return ResourceManager.GetString("OverlayPage_AlignmentTrackpadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller options.
        /// </summary>
        public static string OverlayPage_ControllerOptions {
            get {
                return ResourceManager.GetString("OverlayPage_ControllerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulated controller.
        /// </summary>
        public static string OverlayPage_EmulatedController {
            get {
                return ResourceManager.GetString("OverlayPage_EmulatedController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main trigger.
        /// </summary>
        public static string OverlayPage_MainTrigger {
            get {
                return ResourceManager.GetString("OverlayPage_MainTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the overlay main trigger.
        /// </summary>
        public static string OverlayPage_MainTriggerDesc {
            get {
                return ResourceManager.GetString("OverlayPage_MainTriggerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM controller.
        /// </summary>
        public static string OverlayPage_OEMController {
            get {
                return ResourceManager.GetString("OverlayPage_OEMController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string OverlayPage_Opacity {
            get {
                return ResourceManager.GetString("OverlayPage_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the overlay trackpads opacity.
        /// </summary>
        public static string OverlayPage_OpacityTrackpadDesc {
            get {
                return ResourceManager.GetString("OverlayPage_OpacityTrackpadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string OverlayPage_Overlay {
            get {
                return ResourceManager.GetString("OverlayPage_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay model.
        /// </summary>
        public static string OverlayPage_OverlayModel {
            get {
                return ResourceManager.GetString("OverlayPage_OverlayModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the overlay controller model.
        /// </summary>
        public static string OverlayPage_OverlayModelDesc {
            get {
                return ResourceManager.GetString("OverlayPage_OverlayModelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay preview.
        /// </summary>
        public static string OverlayPage_OverlayPreview {
            get {
                return ResourceManager.GetString("OverlayPage_OverlayPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary trigger.
        /// </summary>
        public static string OverlayPage_SecondaryTrigger {
            get {
                return ResourceManager.GetString("OverlayPage_SecondaryTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the 3D overlay controller trigger.
        /// </summary>
        public static string OverlayPage_SecondaryTriggerDesc {
            get {
                return ResourceManager.GetString("OverlayPage_SecondaryTriggerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the overlay trackpads trigger.
        /// </summary>
        public static string OverlayPage_SecondaryTriggerOverlayDesc {
            get {
                return ResourceManager.GetString("OverlayPage_SecondaryTriggerOverlayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string OverlayPage_Size {
            get {
                return ResourceManager.GetString("OverlayPage_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the 3D overlay controller size.
        /// </summary>
        public static string OverlayPage_SizeDesc {
            get {
                return ResourceManager.GetString("OverlayPage_SizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the overlay trackpads size.
        /// </summary>
        public static string OverlayPage_SizeOverlayDesc {
            get {
                return ResourceManager.GetString("OverlayPage_SizeOverlayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpads options.
        /// </summary>
        public static string OverlayPage_TrackpadsOptions {
            get {
                return ResourceManager.GetString("OverlayPage_TrackpadsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera options.
        /// </summary>
        public static string ProfileSettingsMode0_CameraOptions {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CameraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom response curve.
        /// </summary>
        public static string ProfileSettingsMode0_CustomResponseCurve {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CustomResponseCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output sent to game.
        /// </summary>
        public static string ProfileSettingsMode0_CustomResponseCurveGameOutput {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CustomResponseCurveGameOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement intensity.
        /// </summary>
        public static string ProfileSettingsMode0_CustomResponseIntensity {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CustomResponseIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agressive.
        /// </summary>
        public static string ProfileSettingsMode0_CustomResponsePresetAgressive {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CustomResponsePresetAgressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ProfileSettingsMode0_CustomResponsePresetDefault {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CustomResponsePresetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset options.
        /// </summary>
        public static string ProfileSettingsMode0_CustomResponsePresetOptions {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CustomResponsePresetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precise.
        /// </summary>
        public static string ProfileSettingsMode0_CustomResponsePresetPrecise {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_CustomResponsePresetPrecise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flick Duration.
        /// </summary>
        public static string ProfileSettingsMode0_FlickDuration {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_FlickDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the flick duration, calibrate to 180 degree turn, in milliseconds.
        /// </summary>
        public static string ProfileSettingsMode0_FlickDurationDesc {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_FlickDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flick Stick (Experimental).
        /// </summary>
        public static string ProfileSettingsMode0_FlickStick {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_FlickStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point camera in direction of (right) joystick flick, rotate camera purely in horizontal plane by rotating.
        /// </summary>
        public static string ProfileSettingsMode0_FlickStickDesc {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_FlickStickDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable flick stick.
        /// </summary>
        public static string ProfileSettingsMode0_FlickStickEnable {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_FlickStickEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensivity.
        /// </summary>
        public static string ProfileSettingsMode0_Sensivity {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_Sensivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the motion sensivity of the vertical and horizontal axis.
        /// </summary>
        public static string ProfileSettingsMode0_SensivityDesc {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_SensivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick Sensitivtity.
        /// </summary>
        public static string ProfileSettingsMode0_StickSensitivtity {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_StickSensitivtity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the rotation rate.
        /// </summary>
        public static string ProfileSettingsMode0_StickSensitivtityDesc {
            get {
                return ResourceManager.GetString("ProfileSettingsMode0_StickSensitivtityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadzone.
        /// </summary>
        public static string ProfileSettingsMode1_Deadzone {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_Deadzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the steering deadzone, in degree. Improves steering straight..
        /// </summary>
        public static string ProfileSettingsMode1_DeadzoneDesc {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_DeadzoneDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick Game Input.
        /// </summary>
        public static string ProfileSettingsMode1_JoystickGameInput {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_JoystickGameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick Steering.
        /// </summary>
        public static string ProfileSettingsMode1_JoystickSteering {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_JoystickSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick steering options.
        /// </summary>
        public static string ProfileSettingsMode1_JoystickSteeringOptions {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_JoystickSteeringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick steering preview.
        /// </summary>
        public static string ProfileSettingsMode1_JoystickSteeringPreview {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_JoystickSteeringPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max steering angle.
        /// </summary>
        public static string ProfileSettingsMode1_MaxSteeringAngle {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_MaxSteeringAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the maximum steering angle value, in degree.
        /// </summary>
        public static string ProfileSettingsMode1_MaxSteeringAngleDesc {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_MaxSteeringAngleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering linearity.
        /// </summary>
        public static string ProfileSettingsMode1_SteeringLinearity {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_SteeringLinearity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping between input and steering. Lower values provide more accuracy near full lock but less accuracy near the center. Higher values provide more accuracy near the center but less accuracy near full lock. 1.0 is a linear mapping..
        /// </summary>
        public static string ProfileSettingsMode1_SteeringLinearityDesc {
            get {
                return ResourceManager.GetString("ProfileSettingsMode1_SteeringLinearityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides gyroscope and accelerometer support to Windows handheld gaming computers through a virtual DualShock 4 controller. If the service is enabled, embedded controller will be cloaked to applications outside the whitelist. If the service is disabled, embedded controller will be uncloaked and virtual DualShock 4 controller disabled..
        /// </summary>
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Service.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of input.
        /// </summary>
        public static string StyleofInput {
            get {
                return ResourceManager.GetString("StyleofInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The physical inputs of the controller can be programmed to act like different types of devices.
        /// </summary>
        public static string StyleofInputTooltip {
            get {
                return ResourceManager.GetString("StyleofInputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string StyleofOutput {
            get {
                return ResourceManager.GetString("StyleofOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When sending analog joystick commands to the game, should those commands be a left or right joystick.
        /// </summary>
        public static string StyleofOutputTooltip {
            get {
                return ResourceManager.GetString("StyleofOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this tool as Administrator to unlock these settings..
        /// </summary>
        public static string WarningElevated {
            get {
                return ResourceManager.GetString("WarningElevated", resourceCulture);
            }
        }
    }
}
