//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandheldCompanion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToastEnable {
            get {
                return ((bool)(this["ToastEnable"]));
            }
            set {
                this["ToastEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAtStartup {
            get {
                return ((bool)(this["RunAtStartup"]));
            }
            set {
                this["RunAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartMinimized {
            get {
                return ((bool)(this["StartMinimized"]));
            }
            set {
                this["StartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseMinimises {
            get {
                return ((bool)(this["CloseMinimises"]));
            }
            set {
                this["CloseMinimises"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowLeft {
            get {
                return ((double)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindowTop {
            get {
                return ((double)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MainWindowState {
            get {
                return ((int)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowTheme {
            get {
                return ((int)(this["MainWindowTheme"]));
            }
            set {
                this["MainWindowTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartServiceWithCompanion {
            get {
                return ((bool)(this["StartServiceWithCompanion"]));
            }
            set {
                this["StartServiceWithCompanion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HaltServiceWithCompanion {
            get {
                return ((bool)(this["HaltServiceWithCompanion"]));
            }
            set {
                this["HaltServiceWithCompanion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2022-03-16")]
        public global::System.DateTime UpdateLastChecked {
            get {
                return ((global::System.DateTime)(this["UpdateLastChecked"]));
            }
            set {
                this["UpdateLastChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverlayModel {
            get {
                return ((int)(this["OverlayModel"]));
            }
            set {
                this["OverlayModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int OverlayControllerAlignment {
            get {
                return ((int)(this["OverlayControllerAlignment"]));
            }
            set {
                this["OverlayControllerAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int OverlayControllerSize {
            get {
                return ((int)(this["OverlayControllerSize"]));
            }
            set {
                this["OverlayControllerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public string OverlayControllerTriggerValue {
            get {
                return ((string)(this["OverlayControllerTriggerValue"]));
            }
            set {
                this["OverlayControllerTriggerValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int OverlayTrackpadsAlignment {
            get {
                return ((int)(this["OverlayTrackpadsAlignment"]));
            }
            set {
                this["OverlayTrackpadsAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34")]
        public string OverlayTrackpadsTriggerValue {
            get {
                return ((string)(this["OverlayTrackpadsTriggerValue"]));
            }
            set {
                this["OverlayTrackpadsTriggerValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.25")]
        public double OverlayTrackpadsOpacity {
            get {
                return ((double)(this["OverlayTrackpadsOpacity"]));
            }
            set {
                this["OverlayTrackpadsOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int OverlayTrackpadsSize {
            get {
                return ((int)(this["OverlayTrackpadsSize"]));
            }
            set {
                this["OverlayTrackpadsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentCulture {
            get {
                return ((string)(this["CurrentCulture"]));
            }
            set {
                this["CurrentCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OverlayControllerRestingPitch {
            get {
                return ((double)(this["OverlayControllerRestingPitch"]));
            }
            set {
                this["OverlayControllerRestingPitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OverlayControllerRestingYaw {
            get {
                return ((double)(this["OverlayControllerRestingYaw"]));
            }
            set {
                this["OverlayControllerRestingYaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OverlayControllerRestingRoll {
            get {
                return ((double)(this["OverlayControllerRestingRoll"]));
            }
            set {
                this["OverlayControllerRestingRoll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SensorPlacementUpsideDown {
            get {
                return ((bool)(this["SensorPlacementUpsideDown"]));
            }
            set {
                this["SensorPlacementUpsideDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SensorSelection {
            get {
                return ((int)(this["SensorSelection"]));
            }
            set {
                this["SensorSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SensorPlacement {
            get {
                return ((int)(this["SensorPlacement"]));
            }
            set {
                this["SensorPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverlayControllerFisherPrice {
            get {
                return ((bool)(this["OverlayControllerFisherPrice"]));
            }
            set {
                this["OverlayControllerFisherPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double OverlayRenderInterval {
            get {
                return ((double)(this["OverlayRenderInterval"]));
            }
            set {
                this["OverlayRenderInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverlayRenderAntialiasing {
            get {
                return ((bool)(this["OverlayRenderAntialiasing"]));
            }
            set {
                this["OverlayRenderAntialiasing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HIDmode {
            get {
                return ((int)(this["HIDmode"]));
            }
            set {
                this["HIDmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverlayControllerTriggerType {
            get {
                return ((int)(this["OverlayControllerTriggerType"]));
            }
            set {
                this["OverlayControllerTriggerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverlayTrackpadsTriggerType {
            get {
                return ((int)(this["OverlayTrackpadsTriggerType"]));
            }
            set {
                this["OverlayTrackpadsTriggerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverlayFaceCamera {
            get {
                return ((bool)(this["OverlayFaceCamera"]));
            }
            set {
                this["OverlayFaceCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuickToolsTriggerType {
            get {
                return ((int)(this["QuickToolsTriggerType"]));
            }
            set {
                this["QuickToolsTriggerType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public string QuickToolsTriggerValue {
            get {
                return ((string)(this["QuickToolsTriggerValue"]));
            }
            set {
                this["QuickToolsTriggerValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public double QuickToolsHeight {
            get {
                return ((double)(this["QuickToolsHeight"]));
            }
            set {
                this["QuickToolsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QuickToolsLeft {
            get {
                return ((double)(this["QuickToolsLeft"]));
            }
            set {
                this["QuickToolsLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QuickToolsTop {
            get {
                return ((double)(this["QuickToolsTop"]));
            }
            set {
                this["QuickToolsTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QuickToolsPerformanceTDPSustainedValue {
            get {
                return ((double)(this["QuickToolsPerformanceTDPSustainedValue"]));
            }
            set {
                this["QuickToolsPerformanceTDPSustainedValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QuickToolsPerformanceGPUValue {
            get {
                return ((double)(this["QuickToolsPerformanceGPUValue"]));
            }
            set {
                this["QuickToolsPerformanceGPUValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickToolsPerformanceTDPEnabled {
            get {
                return ((bool)(this["QuickToolsPerformanceTDPEnabled"]));
            }
            set {
                this["QuickToolsPerformanceTDPEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickToolsPerformanceGPUEnabled {
            get {
                return ((bool)(this["QuickToolsPerformanceGPUEnabled"]));
            }
            set {
                this["QuickToolsPerformanceGPUEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int QuickToolsPowerModeValue {
            get {
                return ((int)(this["QuickToolsPowerModeValue"]));
            }
            set {
                this["QuickToolsPowerModeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QuickToolsPerformanceTDPBoostValue {
            get {
                return ((double)(this["QuickToolsPerformanceTDPBoostValue"]));
            }
            set {
                this["QuickToolsPerformanceTDPBoostValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfigurableTDPOverride {
            get {
                return ((bool)(this["ConfigurableTDPOverride"]));
            }
            set {
                this["ConfigurableTDPOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ConfigurableTDPOverrideUp {
            get {
                return ((double)(this["ConfigurableTDPOverrideUp"]));
            }
            set {
                this["ConfigurableTDPOverrideUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ConfigurableTDPOverrideDown {
            get {
                return ((double)(this["ConfigurableTDPOverrideDown"]));
            }
            set {
                this["ConfigurableTDPOverrideDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double OverlayControllerOpacity {
            get {
                return ((double)(this["OverlayControllerOpacity"]));
            }
            set {
                this["OverlayControllerOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public string OverlayControllerBackgroundColor {
            get {
                return ((string)(this["OverlayControllerBackgroundColor"]));
            }
            set {
                this["OverlayControllerBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowPrevState {
            get {
                return ((int)(this["MainWindowPrevState"]));
            }
            set {
                this["MainWindowPrevState"] = value;
            }
        }
    }
}
