//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControllerHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Options]
        ///UseInitBeep=1
        ///Log=0
        ///Console=0
        ///DebugMode=0
        ///InternetDatabaseUrl=http://www.x360ce.com/webservices/x360ce.asmx
        ///InternetFeatures=1
        ///InternetAutoload=1
        ///AllowOnlyOneCopy=1
        ///ProgramScanLocations=C:\Program Files,C:\Program Files (x86)
        ///Version=2
        ///CombineEnabled=0
        ///ExcludeSupplementalDevices=0
        ///ExcludeVirtualDevices=0
        ///
        ///[InputHook]
        ///HookMode=1
        ///
        ///[Mappings]
        ///PAD1=VirtualDS4
        ///PAD2=
        ///PAD3=
        ///PAD4=
        ///
        ///[PAD1]
        ///[PAD2]
        ///[PAD3]
        ///[PAD4]
        ///
        ///[VirtualDS4]
        ///ProductName=Wireless Controller
        ///ProductGuid=05c4054c [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string DualShock4 {
            get {
                return ResourceManager.GetString("DualShock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Options]
        ///UseInitBeep=1
        ///Log=0
        ///Console=0
        ///DebugMode=0
        ///InternetDatabaseUrl=http://www.x360ce.com/webservices/x360ce.asmx
        ///InternetFeatures=1
        ///InternetAutoload=1
        ///AllowOnlyOneCopy=1
        ///ProgramScanLocations=C:\Program Files,C:\Program Files (x86)
        ///Version=2
        ///CombineEnabled=0
        ///ExcludeSupplementalDevices=0
        ///ExcludeVirtualDevices=0
        ///
        ///[InputHook]
        ///HookMode=1
        ///
        ///[Mappings]
        ///PAD1=VirtualDS4
        ///PAD2=
        ///PAD3=
        ///PAD4=
        ///
        ///[PAD1]
        ///[PAD2]
        ///[PAD3]
        ///[PAD4]
        ///
        ///[VirtualDS4]
        ///ProductName=Wireless Controller
        ///ProductGuid=05c4054c [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Xbox360 {
            get {
                return ResourceManager.GetString("Xbox360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_1 {
            get {
                object obj = ResourceManager.GetObject("xinput1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_11 {
            get {
                object obj = ResourceManager.GetObject("xinput1_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_2 {
            get {
                object obj = ResourceManager.GetObject("xinput1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_21 {
            get {
                object obj = ResourceManager.GetObject("xinput1_21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_3 {
            get {
                object obj = ResourceManager.GetObject("xinput1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_31 {
            get {
                object obj = ResourceManager.GetObject("xinput1_31", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_4 {
            get {
                object obj = ResourceManager.GetObject("xinput1_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_41 {
            get {
                object obj = ResourceManager.GetObject("xinput1_41", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput9_1_0 {
            get {
                object obj = ResourceManager.GetObject("xinput9_1_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] xinput9_1_01 {
            get {
                object obj = ResourceManager.GetObject("xinput9_1_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
