//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControllerHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Options]
        ///UseInitBeep=1
        ///Log=0
        ///Console=0
        ///DebugMode=0
        ///InternetDatabaseUrl=http://www.x360ce.com/webservices/x360ce.asmx
        ///InternetFeatures=1
        ///InternetAutoload=1
        ///AllowOnlyOneCopy=1
        ///ProgramScanLocations=C:\Program Files,C:\Program Files (x86)
        ///Version=2
        ///CombineEnabled=0
        ///ExcludeSupplementalDevices=0
        ///ExcludeVirtualDevices=0
        ///
        ///[InputHook]
        ///HookMode=1
        ///
        ///[Mappings]
        ///PAD1=VirtualDS4
        ///PAD2=
        ///PAD3=
        ///PAD4=
        ///
        ///[PAD1]
        ///[PAD2]
        ///[PAD3]
        ///[PAD4]
        ///
        ///[VirtualDS4]
        ///ProductName=Wireless Controller
        ///ProductGuid=05c4054c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string x360ce {
            get {
                return ResourceManager.GetString("x360ce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_1 {
            get {
                object obj = ResourceManager.GetObject("xinput1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_11 {
            get {
                object obj = ResourceManager.GetObject("xinput1_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_2 {
            get {
                object obj = ResourceManager.GetObject("xinput1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_21 {
            get {
                object obj = ResourceManager.GetObject("xinput1_21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_3 {
            get {
                object obj = ResourceManager.GetObject("xinput1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_31 {
            get {
                object obj = ResourceManager.GetObject("xinput1_31", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_4 {
            get {
                object obj = ResourceManager.GetObject("xinput1_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_41 {
            get {
                object obj = ResourceManager.GetObject("xinput1_41", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput9_1_0 {
            get {
                object obj = ResourceManager.GetObject("xinput9_1_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput9_1_01 {
            get {
                object obj = ResourceManager.GetObject("xinput9_1_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
