//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControllerCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;AYASpace&quot;,
        ///  &quot;path&quot;: &quot;AYASpace.exe&quot;,
        ///  &quot;executable&quot;: &quot;AYASpace.exe&quot;,
        ///  &quot;whitelisted&quot;: false
        ///}.
        /// </summary>
        public static string AYASpace_json {
            get {
                return ResourceManager.GetString("AYASpace.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Cemu&quot;,
        ///  &quot;path&quot;: &quot;Cemu.exe&quot;,
        ///  &quot;executable&quot;: &quot;Cemu.exe&quot;,
        ///  &quot;whitelisted&quot;: false
        ///}.
        /// </summary>
        public static string Cemu_json {
            get {
                return ResourceManager.GetString("Cemu.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;ControllerCompanion&quot;,
        ///  &quot;path&quot;: &quot;ControllerCompanion.exe&quot;,
        ///  &quot;executable&quot;: &quot;ControllerCompanion.exe&quot;,
        ///  &quot;whitelisted&quot;: true
        ///}.
        /// </summary>
        public static string ControllerCompanion_json {
            get {
                return ResourceManager.GetString("ControllerCompanion.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Default&quot;,
        ///  &quot;path&quot;: &quot;&quot;,
        ///  &quot;executable&quot;: &quot;Default.exe&quot;,
        ///  &quot;isDefault&quot;: true,
        ///  &quot;whitelisted&quot;: false,
        ///  &quot;umc_enabled&quot;: false
        ///}.
        /// </summary>
        public static string Default_json {
            get {
                return ResourceManager.GetString("Default.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Dolphin&quot;,
        ///  &quot;path&quot;: &quot;Dolphin.exe&quot;,
        ///  &quot;executable&quot;: &quot;Dolphin.exe&quot;,
        ///  &quot;whitelisted&quot;: true
        ///}.
        /// </summary>
        public static string Dolphin_json {
            get {
                return ResourceManager.GetString("Dolphin.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button A.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_A {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_AlwaysOn {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.AlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button B.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_B {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_Back {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad Down.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_DPadDown {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.DPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad Left.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_DPadLeft {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.DPadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad Right.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_DPadRight {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.DPadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad Up.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_DPadUp {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.DPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Shoulder.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_LeftShoulder {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.LeftShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_LeftThumb {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.LeftThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Trigger.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_LeftTrigger {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.LeftTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Shoulder.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_RightShoulder {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.RightShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_RightThumb {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.RightThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Trigger.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_RightTrigger {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.RightTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_Start {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button X.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_X {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Y.
        /// </summary>
        public static string Enum_GamepadButtonFlagsExt_Y {
            get {
                return ResourceManager.GetString("Enum.GamepadButtonFlagsExt.Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulated DualShock 4 controller.
        /// </summary>
        public static string Enum_HIDmode_DualShock4Controller {
            get {
                return ResourceManager.GetString("Enum.HIDmode.DualShock4Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No emulated controller.
        /// </summary>
        public static string Enum_HIDmode_NoController {
            get {
                return ResourceManager.GetString("Enum.HIDmode.NoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulated XBOX 360 controller.
        /// </summary>
        public static string Enum_HIDmode_Xbox360Controller {
            get {
                return ResourceManager.GetString("Enum.HIDmode.Xbox360Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Enum_HIDstatus_Connected {
            get {
                return ResourceManager.GetString("Enum.HIDstatus.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Enum_HIDstatus_Disconnected {
            get {
                return ResourceManager.GetString("Enum.HIDstatus.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick camera.
        /// </summary>
        public static string Enum_Input_JoystickCamera {
            get {
                return ResourceManager.GetString("Enum.Input.JoystickCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick steering.
        /// </summary>
        public static string Enum_Input_JoystickSteering {
            get {
                return ResourceManager.GetString("Enum.Input.JoystickSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player space.
        /// </summary>
        public static string Enum_Input_PlayerSpace {
            get {
                return ResourceManager.GetString("Enum.Input.PlayerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left joystick.
        /// </summary>
        public static string Enum_Output_LeftStick {
            get {
                return ResourceManager.GetString("Enum.Output.LeftStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right joystick.
        /// </summary>
        public static string Enum_Output_RightStick {
            get {
                return ResourceManager.GetString("Enum.Output.RightStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your default controller profile. This profile will be applied for all your applications that do not have a specific profile. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_IsDefault {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems this profile excutable is running. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_IsRunning {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems this profile does not have an executable. How is this even possible?.
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingExecutable {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems this profile does not have a path to the application. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingPath {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems you do not have the necessary permission level to modify the content of this application. Make sure you have started this program in administrator mode..
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingPermission {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to see here..
        /// </summary>
        public static string Enum_ProfileErrorCode_None {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Enum_ServiceStartMode_Automatic {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Enum_ServiceStartMode_Disabled {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Enum_ServiceStartMode_Manual {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input will operate as a simple joystick. This is intended for traditional joystick applications.
        /// </summary>
        public static string JoystickCameraDesc {
            get {
                return ResourceManager.GetString("JoystickCameraDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input will operate as a joystick optimized for controlling a steering wheel or a racing game.
        /// </summary>
        public static string JoystickSteeringDesc {
            get {
                return ResourceManager.GetString("JoystickSteeringDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Joyxoff&quot;,
        ///  &quot;path&quot;: &quot;Joyxoff.exe&quot;,
        ///  &quot;executable&quot;: &quot;Joyxoff.exe&quot;,
        ///  &quot;whitelisted&quot;: true
        ///}.
        /// </summary>
        public static string JoyXOff_json {
            get {
                return ResourceManager.GetString("JoyXOff.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input will operate as a joystick optimized for controlling a first or third person camera.
        /// </summary>
        public static string PlayerSpaceDesc {
            get {
                return ResourceManager.GetString("PlayerSpaceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Playnite.FullscreenApp&quot;,
        ///  &quot;path&quot;: &quot;Playnite.FullscreenApp.exe&quot;,
        ///  &quot;executable&quot;: &quot;Playnite.FullscreenApp.exe&quot;,
        ///  &quot;whitelisted&quot;: true
        ///}.
        /// </summary>
        public static string Playnite_FullscreenApp_json {
            get {
                return ResourceManager.GetString("Playnite.FullscreenApp.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Power Control Panel&quot;,
        ///  &quot;path&quot;: &quot;Power Control Panel.exe&quot;,
        ///  &quot;executable&quot;: &quot;Power Control Panel.exe&quot;,
        ///  &quot;whitelisted&quot;: true
        ///}
        ///.
        /// </summary>
        public static string PowerControlPanel_json {
            get {
                return ResourceManager.GetString("PowerControlPanel.json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Yuzu&quot;,
        ///  &quot;path&quot;: &quot;yuzu.exe&quot;,
        ///  &quot;executable&quot;: &quot;yuzu.exe&quot;,
        ///  &quot;whitelisted&quot;: false
        ///}.
        /// </summary>
        public static string Yuzu_json {
            get {
                return ResourceManager.GetString("Yuzu.json", resourceCulture);
            }
        }
    }
}
