//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControllerCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input will operate as a simple joystick. Ideal for laptop and clamshell type handhelds, automatic yaw roll swap based on how device is being held (90 or 180 degree open)..
        /// </summary>
        public static string AutoRollYawSwapDesc {
            get {
                return ResourceManager.GetString("AutoRollYawSwapDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYA.
        /// </summary>
        public static string Enum_AYANEO2_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.AYANEO2.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≈.
        /// </summary>
        public static string Enum_AYANEO2_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.AYANEO2.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC.
        /// </summary>
        public static string Enum_AYANEO2_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.AYANEO2.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string Enum_AYANEO2_ButtonFlags_OEM4 {
            get {
                return ResourceManager.GetString("Enum.AYANEO2.ButtonFlags.OEM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Enum_AYANEO2021Pro_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.AYANEO2021Pro.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esc.
        /// </summary>
        public static string Enum_AYANEO2021Pro_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.AYANEO2021Pro.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string Enum_AYANEO2021Pro_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.AYANEO2021Pro.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYA.
        /// </summary>
        public static string Enum_AYANEOAIR_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIR.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≈.
        /// </summary>
        public static string Enum_AYANEOAIR_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIR.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC.
        /// </summary>
        public static string Enum_AYANEOAIR_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIR.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string Enum_AYANEOAIR_ButtonFlags_OEM4 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIR.ButtonFlags.OEM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYA.
        /// </summary>
        public static string Enum_AYANEOAIRLite_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRLite.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≈.
        /// </summary>
        public static string Enum_AYANEOAIRLite_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRLite.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC.
        /// </summary>
        public static string Enum_AYANEOAIRLite_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRLite.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string Enum_AYANEOAIRLite_ButtonFlags_OEM4 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRLite.ButtonFlags.OEM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYA.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ≈.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM4 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B1 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B2 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B3 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B4 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_Back {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sony.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_Special {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_Start {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulated DualShock 4 controller.
        /// </summary>
        public static string Enum_HIDmode_DualShock4Controller {
            get {
                return ResourceManager.GetString("Enum.HIDmode.DualShock4Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No emulated controller.
        /// </summary>
        public static string Enum_HIDmode_NoController {
            get {
                return ResourceManager.GetString("Enum.HIDmode.NoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulated XBOX 360 controller.
        /// </summary>
        public static string Enum_HIDmode_Xbox360Controller {
            get {
                return ResourceManager.GetString("Enum.HIDmode.Xbox360Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Enum_HIDstatus_Connected {
            get {
                return ResourceManager.GetString("Enum.HIDstatus.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Enum_HIDstatus_Disconnected {
            get {
                return ResourceManager.GetString("Enum.HIDstatus.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Roll Yaw Swap.
        /// </summary>
        public static string Enum_Input_AutoRollYawSwap {
            get {
                return ResourceManager.GetString("Enum.Input.AutoRollYawSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick camera.
        /// </summary>
        public static string Enum_Input_JoystickCamera {
            get {
                return ResourceManager.GetString("Enum.Input.JoystickCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick steering.
        /// </summary>
        public static string Enum_Input_JoystickSteering {
            get {
                return ResourceManager.GetString("Enum.Input.JoystickSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player space.
        /// </summary>
        public static string Enum_Input_PlayerSpace {
            get {
                return ResourceManager.GetString("Enum.Input.PlayerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Enum_InputsHotkeyType_Custom {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Enum_InputsHotkeyType_Device {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handheld Companion.
        /// </summary>
        public static string Enum_InputsHotkeyType_Handheld {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Handheld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handheld Companion.
        /// </summary>
        public static string Enum_InputsHotkeyType_HC {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string Enum_InputsHotkeyType_Overlay {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick tools.
        /// </summary>
        public static string Enum_InputsHotkeyType_Quicktools {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Quicktools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Enum_InputsHotkeyType_Windows {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Roll Yaw Swap.
        /// </summary>
        public static string Enum_MotionInput_AutoRollYawSwap {
            get {
                return ResourceManager.GetString("Enum.MotionInput.AutoRollYawSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick Camera.
        /// </summary>
        public static string Enum_MotionInput_JoystickCamera {
            get {
                return ResourceManager.GetString("Enum.MotionInput.JoystickCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick Steering.
        /// </summary>
        public static string Enum_MotionInput_JoystickSteering {
            get {
                return ResourceManager.GetString("Enum.MotionInput.JoystickSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Space.
        /// </summary>
        public static string Enum_MotionInput_PlayerSpace {
            get {
                return ResourceManager.GetString("Enum.MotionInput.PlayerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Stick.
        /// </summary>
        public static string Enum_MotionOutput_LeftStick {
            get {
                return ResourceManager.GetString("Enum.MotionOutput.LeftStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Stick.
        /// </summary>
        public static string Enum_MotionOutput_RightStick {
            get {
                return ResourceManager.GetString("Enum.MotionOutput.RightStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B1 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B2 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B3 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B4 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_Back {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEAM.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_Special {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_Start {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left joystick.
        /// </summary>
        public static string Enum_Output_LeftStick {
            get {
                return ResourceManager.GetString("Enum.Output.LeftStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right joystick.
        /// </summary>
        public static string Enum_Output_RightStick {
            get {
                return ResourceManager.GetString("Enum.Output.RightStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your default controller profile. This profile will be applied for all your applications that do not have a specific profile. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_Default {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems this profile does not have an executable. How is this even possible?.
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingExecutable {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems this profile does not have a path to the application. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingPath {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems you do not have the necessary permission level to modify the content of this application. Make sure you have started this program in administrator mode..
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingPermission {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to see here..
        /// </summary>
        public static string Enum_ProfileErrorCode_None {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. It seems this profile excutable is running. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_Running {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Enum_QualityOfServiceLevel_Default {
            get {
                return ResourceManager.GetString("Enum.QualityOfServiceLevel.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco.
        /// </summary>
        public static string Enum_QualityOfServiceLevel_Eco {
            get {
                return ResourceManager.GetString("Enum.QualityOfServiceLevel.Eco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Enum_QualityOfServiceLevel_High {
            get {
                return ResourceManager.GetString("Enum.QualityOfServiceLevel.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command center.
        /// </summary>
        public static string Enum_ROGAlly_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.ROGAlly.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armory crate.
        /// </summary>
        public static string Enum_ROGAlly_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.ROGAlly.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1 / M2.
        /// </summary>
        public static string Enum_ROGAlly_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.ROGAlly.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Enum_ServiceStartMode_Automatic {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Enum_ServiceStartMode_Disabled {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Enum_ServiceStartMode_Manual {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Enum_SteamDeck_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.SteamDeck.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2.
        /// </summary>
        public static string Enum_XInputController_AxisLayoutFlags_L2 {
            get {
                return ResourceManager.GetString("Enum.XInputController.AxisLayoutFlags.L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb.
        /// </summary>
        public static string Enum_XInputController_AxisLayoutFlags_LeftThumb {
            get {
                return ResourceManager.GetString("Enum.XInputController.AxisLayoutFlags.LeftThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2.
        /// </summary>
        public static string Enum_XInputController_AxisLayoutFlags_R2 {
            get {
                return ResourceManager.GetString("Enum.XInputController.AxisLayoutFlags.R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb.
        /// </summary>
        public static string Enum_XInputController_AxisLayoutFlags_RightThumb {
            get {
                return ResourceManager.GetString("Enum.XInputController.AxisLayoutFlags.RightThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B1 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B2 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B3 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B4 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B5.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B5 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B6.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B6 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B7.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B7 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B8.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B8 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_Back {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad Down.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_DPadDown {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.DPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad Left.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_DPadLeft {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.DPadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPad Right.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_DPadRight {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.DPadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPad Up.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_DPadUp {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.DPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LB.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_L1 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L2.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_L2 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L3.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_L3 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L4.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_L4 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.L4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L5.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_L5 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.L5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_LeftThumb {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.LeftThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb Down.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_LeftThumbDown {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.LeftThumbDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb Left.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_LeftThumbLeft {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.LeftThumbLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb Right.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_LeftThumbRight {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.LeftThumbRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb Up.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_LeftThumbUp {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.LeftThumbUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM1.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM2.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM3.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RB.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_R1 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_R2 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R3.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_R3 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R4.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_R4 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.R4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R5.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_R5 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.R5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_RightThumb {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.RightThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb Down.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_RightThumbDown {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.RightThumbDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb Left.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_RightThumbLeft {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.RightThumbLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb Right.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_RightThumbRight {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.RightThumbRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb Up.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_RightThumbUp {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.RightThumbUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_Special {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_Start {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input will operate as a simple joystick. This is intended for traditional joystick applications.
        /// </summary>
        public static string JoystickCameraDesc {
            get {
                return ResourceManager.GetString("JoystickCameraDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input will operate as a joystick optimized for controlling a steering wheel or a racing game.
        /// </summary>
        public static string JoystickSteeringDesc {
            get {
                return ResourceManager.GetString("JoystickSteeringDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input will operate as a joystick optimized for controlling a first or third person camera.
        /// </summary>
        public static string PlayerSpaceDesc {
            get {
                return ResourceManager.GetString("PlayerSpaceDesc", resourceCulture);
            }
        }
    }
}
