//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControllerCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This input will operate as a simple joystick. Ideal for laptop and clamshell type handhelds, automatic yaw roll swap based on how device is being held (90 or 180 degree open)..
        /// </summary>
        public static string AutoRollYawSwapDesc {
            get {
                return ResourceManager.GetString("AutoRollYawSwapDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AYA.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM1 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à =.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM2 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RC.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM3 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LC.
        /// </summary>
        public static string Enum_AYANEOAIRPro_ButtonFlags_OEM4 {
            get {
                return ResourceManager.GetString("Enum.AYANEOAIRPro.ButtonFlags.OEM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cross.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B1 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Circle.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B2 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Square.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B3 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triangle.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_B4 {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_Back {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sony.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_Special {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string Enum_DS4Controller_ButtonFlags_Start {
            get {
                return ResourceManager.GetString("Enum.DS4Controller.ButtonFlags.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emulated DualShock 4 controller.
        /// </summary>
        public static string Enum_HIDmode_DualShock4Controller {
            get {
                return ResourceManager.GetString("Enum.HIDmode.DualShock4Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No emulated controller.
        /// </summary>
        public static string Enum_HIDmode_NoController {
            get {
                return ResourceManager.GetString("Enum.HIDmode.NoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emulated XBOX 360 controller.
        /// </summary>
        public static string Enum_HIDmode_Xbox360Controller {
            get {
                return ResourceManager.GetString("Enum.HIDmode.Xbox360Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        public static string Enum_HIDstatus_Connected {
            get {
                return ResourceManager.GetString("Enum.HIDstatus.Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnected.
        /// </summary>
        public static string Enum_HIDstatus_Disconnected {
            get {
                return ResourceManager.GetString("Enum.HIDstatus.Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto Roll Yaw Swap.
        /// </summary>
        public static string Enum_Input_AutoRollYawSwap {
            get {
                return ResourceManager.GetString("Enum.Input.AutoRollYawSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joystick camera.
        /// </summary>
        public static string Enum_Input_JoystickCamera {
            get {
                return ResourceManager.GetString("Enum.Input.JoystickCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Joystick steering.
        /// </summary>
        public static string Enum_Input_JoystickSteering {
            get {
                return ResourceManager.GetString("Enum.Input.JoystickSteering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Player space.
        /// </summary>
        public static string Enum_Input_PlayerSpace {
            get {
                return ResourceManager.GetString("Enum.Input.PlayerSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Handheld Companion.
        /// </summary>
        public static string Enum_InputsHotkeyType_HC {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overlay.
        /// </summary>
        public static string Enum_InputsHotkeyType_Overlay {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quick tools.
        /// </summary>
        public static string Enum_InputsHotkeyType_Quicktools {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Quicktools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows.
        /// </summary>
        public static string Enum_InputsHotkeyType_Windows {
            get {
                return ResourceManager.GetString("Enum.InputsHotkeyType.Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B1 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B2 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B3 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_B4 {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_Back {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        public static string Enum_NeptuneController_ButtonFlags_Start {
            get {
                return ResourceManager.GetString("Enum.NeptuneController.ButtonFlags.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left joystick.
        /// </summary>
        public static string Enum_Output_LeftStick {
            get {
                return ResourceManager.GetString("Enum.Output.LeftStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right joystick.
        /// </summary>
        public static string Enum_Output_RightStick {
            get {
                return ResourceManager.GetString("Enum.Output.RightStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is your default controller profile. This profile will be applied for all your applications that do not have a specific profile. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_Default {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oops. It seems this profile does not have an executable. How is this even possible?.
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingExecutable {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oops. It seems this profile does not have a path to the application. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingPath {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oops. It seems you do not have the necessary permission level to modify the content of this application. Make sure you have started this program in administrator mode..
        /// </summary>
        public static string Enum_ProfileErrorCode_MissingPermission {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.MissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nothing to see here..
        /// </summary>
        public static string Enum_ProfileErrorCode_None {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oops. It seems this profile excutable is running. Some options requiring an executable might be disabled..
        /// </summary>
        public static string Enum_ProfileErrorCode_Running {
            get {
                return ResourceManager.GetString("Enum.ProfileErrorCode.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        public static string Enum_QualityOfServiceLevel_Default {
            get {
                return ResourceManager.GetString("Enum.QualityOfServiceLevel.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eco.
        /// </summary>
        public static string Enum_QualityOfServiceLevel_Eco {
            get {
                return ResourceManager.GetString("Enum.QualityOfServiceLevel.Eco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High.
        /// </summary>
        public static string Enum_QualityOfServiceLevel_High {
            get {
                return ResourceManager.GetString("Enum.QualityOfServiceLevel.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic.
        /// </summary>
        public static string Enum_ServiceStartMode_Automatic {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled.
        /// </summary>
        public static string Enum_ServiceStartMode_Disabled {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manual.
        /// </summary>
        public static string Enum_ServiceStartMode_Manual {
            get {
                return ResourceManager.GetString("Enum.ServiceStartMode.Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B1 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B2 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B3 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_B4 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_Back {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LB.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_L1 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RB.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_R1 {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guide.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_Special {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        public static string Enum_XInputController_ButtonFlags_Start {
            get {
                return ResourceManager.GetString("Enum.XInputController.ButtonFlags.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This input will operate as a simple joystick. This is intended for traditional joystick applications.
        /// </summary>
        public static string JoystickCameraDesc {
            get {
                return ResourceManager.GetString("JoystickCameraDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This input will operate as a joystick optimized for controlling a steering wheel or a racing game.
        /// </summary>
        public static string JoystickSteeringDesc {
            get {
                return ResourceManager.GetString("JoystickSteeringDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This input will operate as a joystick optimized for controlling a first or third person camera.
        /// </summary>
        public static string PlayerSpaceDesc {
            get {
                return ResourceManager.GetString("PlayerSpaceDesc", resourceCulture);
            }
        }
    }
}
